language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - jruby-9.1.13.0
  - jruby-head
  - ruby-head
matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
